version: "2.0"

services:
  backend:
    image: ninja35sahu/ai-backend:latest
    env:
      - MODEL_NAME=Meta-Llama-3-1-8B-Instruct-FP8
    expose:
      - port: 8000
        as: 80
        to:
          - global: true   # expose FastAPI to internet
      - port: 8001
        as: 8001
        to:
          - global: false  # internal use (only backend calls)
    resources:
      cpu:
        units: 4
      memory:
        size: 32Gi
      gpu:
        units: 1
        attributes:
          vendor:
            nvidia:
      storage:
        - size: 50Gi

  frontend:
    image: ankit040706/frontend:latest
    expose:
      - port: 80
        as: 3000
        to:
          - global: true
    resources:
      cpu:
        units: 1
      memory:
        size: 1Gi
      storage:
        - size: 1Gi

profiles:
  compute:
    backend:
      resources:
        cpu:
          units: 4
        memory:
          size: 32Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
        storage:
          - size: 50Gi
    frontend:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          - size: 1Gi

  placement:
    dcloud:
      pricing:
        backend:
          denom: uakt
          amount: 1000
        frontend:
          denom: uakt
          amount: 100

deployment:
  backend:
    dcloud:
      profile: backend
      count: 1
  frontend:
    dcloud:
      profile: frontend
      count: 1
